/* Main.c file generated by New Project wizard
 *
 * Created:   Sun Jul 27 2025
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#define lcd P2

sbit led = P1^2;
sbit rs = P1^0;
sbit en = P1^1;

// Delay function
void delay(unsigned int ms) {
    unsigned int i, j;
    for(i = 0; i < ms; i++)
        for(j = 0; j < 1275; j++);
}

// Send command to LCD
void lcd_cmd(unsigned char cmd) {
    rs = 0;
    lcd = cmd;
    en = 1;
    delay(1);
    en = 0;
}

// Send data (character) to LCD
void lcd_data(unsigned char ch) {
    rs = 1;
    lcd = ch;
    en = 1;
    delay(1);
    en = 0;
}

// Print string to LCD
void lcd_print(char *str) {
    while(*str)
        lcd_data(*str++);
}

// Initialize LCD
void lcd_init() {
    lcd_cmd(0x38); // 2 lines, 5x7 matrix
    lcd_cmd(0x0C); // Display ON, Cursor OFF
    lcd_cmd(0x01); // Clear screen
    lcd_cmd(0x06); // Entry mode
    lcd_cmd(0x80); // Cursor at beginning
}

// External Interrupt Handler
void inter_ISR(void) interrupt 2 {
    led = ~led;
    lcd_cmd(0x80);        // First line
    lcd_print("LED: ");   // Static text

    // Clear or overwrite old state
    lcd_cmd(0x86);        // Move cursor to right of "LED: "
    if (led)
        lcd_print("ON ");
    else
        lcd_print("OFF  ");
}

void main(void) {
    led = 0;
    lcd_init();

    lcd_cmd(0x80);
    lcd_print("LED: OFF");

    IT1 = 1;  // Falling edge triggered INT1
    EA = 1;   // Enable global interrupts
    EX1 = 1;  // Enable INT1

    while(1);
}
