/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Jul 24 2025
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
sbit P1_1=P1^1;

delay_high()
{
   TMOD=0x01;   
   TL0=0xE0;
   TH0=0xFC;
   TR0=1;
   while(TF0==0);  // 80% duty cycle;
   TF0=0;
   TR0=0;
}

delay_low()
{
   TMOD=0x01;   
   TL0=0x38;
   TH0=0xFF;
   TR0=1;
   while(TF0==0);   // 20% duty cycle;
   TF0=0;
   TR0=0;
}

void main(void)
 { 
   while(1)
      {
	 P1_1=1;
	 delay_high();
	 
	 P1_1=0;
	 delay_low();
	 }
 }