/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Aug 25 2025
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

sbit st1=P2^0;
sbit st2=P2^1;
sbit st3=P2^2;
sbit st4=P2^3;

void time_delay(unsigned int t)
{
   unsigned int i,j;
   for( i=0;i<t;i++)
    {
      for(j=0;j<1275;j++);
    }
}
void full_forward_rot()         // clock wise direction
{
   st1=0;st2=0;st3=0;st4=1;
   time_delay(100);
    st1=0;st2=0;st3=1;st4=0;
   time_delay(100);
    st1=0;st2=1;st3=0;st4=0;
   time_delay(100);
    st1=1;st2=0;st3=0;st4=0;
   time_delay(100);
   
}

void full_reverse_rot(){         // Anti_clock wise direction
   
   st1=1;st2=0;st3=0;st4=1;
   time_delay(100);
    st1=0;st2=1;st3=0;st4=0;
   time_delay(100);
    st1=0;st2=0;st3=1;st4=0;
   time_delay(100);
    st1=0;st2=0;st3=0;st4=1;
   time_delay(100);
   
}
void main(void)
 { 
    while(1)
  {
    full_forward_rot();
     time_delay(500);
     full_reverse_rot();
     time_delay(500);
  }
    
   
 }