/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Jul 21 2025
 * Processor: AT89C51
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>
sbit P1_1 =P1^1;

void delay(unsigned int ms)
{
   unsigned i,j;
   for(i=0;i<ms;i++){
      for(j=0;j<250;j++);
      
      }
}
void main(void)
 { 
   // Write your code here
   while (1)
      {
	 P1_1=0;
	 delay(500);
	 P1_1=1;
	  delay(500);
	 
	 
	 }
      
 }