/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Aug 11 2025
 * Processor: 80C51
 * Compiler:  Keil for 8051
 */
 
 /*  Traffic light management system;
     three led are used red,yellow & green in port 2 pin 0,3th,4th pins;
    Two interrupt are use for controlled by Offecers;
    Ext0 for 'ON' green led for Road A,
    Ext1 for 'ON' green led for Road B, where any Vehicals presence.
 */

#include <reg51.h>
#include <stdio.h>

// Road A;
sbit red_A=P2^0;
sbit yellow_A=P2^3;
sbit green_A=P2^4;

//Road B;
sbit red_B=P1^0;
sbit yellow_B=P1^2;
sbit green_B=P1^7;

void delay_ms(unsigned int ms)
{
    unsigned int i, j;   // Declare variables here
    for(i = 0; i < ms; i++)
    {
        for(j = 0; j < 1256; j++);
    }
}


void INT0_ISR() interrupt 0
{
   green_A=1;red_A=0;yellow_A=0;
   green_B=0;red_B=1;yellow_B=0;
   delay_ms(500);   
   
}

void INT1_ISR() interrupt 2
{
   green_A=0;red_A=1;yellow_A=0;
   green_B=1;red_B=0;yellow_B=0;
   delay_ms(500);   
   
}


void main(void)
 { 
   EA=1;
   IT0=1;
   IT1=1;
   EX0=1;
   EX1=1;
   
   red_A=0;yellow_A=0;green_A=1;
   red_B=1;yellow_B=0;green_B=0; 
   delay_ms(500);
    
   red_A=1;yellow_A=0;green_A=0;
   red_B=0;yellow_B=1;green_B=0; 
   delay_ms(500);
   
   red_A=0;yellow_A=1;green_A=0;
   red_B=0;yellow_B=0;green_B=1; 
   delay_ms(500);
    
 }